import random
import pandas as pd

# Function to simulate the Asch experiment and determine validity
def asch(ref, A, B, C, rep):
    if ref == A:
        if rep == 1:
            return True
        else:
            return False
    elif ref == B:
        if rep == 2:
            return True
        else:
            return False
    elif ref == C:
        if rep == 3:
            return True
        else:
            return False
    return False

#Generer 10 random test cases that are true

octavia_test = []

for i in range(10): 
    values = [random.choice(range(1, 25)) for j in range(3)]
    A, B, C = values
    ref = random.choice(values)
    rep = values.index(ref) + 1 ## +1 because rep should be 1, 2, or 3

    valid = asch(ref, A, B, C, rep) #valid True if rep correctly identifies which of A, B, or C matches ref, and False otherwise.
    octavia_test.append([ref, A, B, C, rep, valid])

#create df for test dataset

columns = ['ref', 'A', 'B', 'C', 'rep', 'valid']
test_df = pd.DataFrame(octavia_test, columns=columns)

# Show the test dataset
print(test_df)

# save the test dataset 
test_df.to_csv('8_octavia_asch_test_dataset_10.csv', index=False) #index false means index generated by pandas wont be saved in ds
